### ISSUE TITLE
About page

### ISSUE THREAD

**Issue by the-tave** [iscience-kn/dropR#12]
I'd like to format the about page similar to the Home-Tab so that the text is less wide and easier to read. I remember Ulf mentioned that he would like to have some proper sourcees and more text on here as well - I'll ask him about it tomorrow. 
@mbannert do you think it would make sense to have it rendered by a seperate Rmd file? Something like the Deep Dive page here: https://the-tave.shinyapps.io/Statistics-Picker/ (under active development ;) )

**Comment by mbannert** [comment]
I'd first put the text together maybe discuss here and then discuss the implementation. .rmd. Is an option, plain html, too.

**Comment by the-tave** [comment]
Ulf mentioned that he would like the page to include one or two papers on dropout in general and our dropR paper in the future as well. Therefore I think I would just write up the text directly in the ui and add references manually if necessary!
