### ISSUE TITLE
Single NAs in demo data

### ISSUE THREAD

**Issue by the-tave** [iscience-kn/dropR#17]
While trying to figure out the issue on my data that I tried to analyze with dropR, I notived that there was no check for single missings in the data. So I implemented one inspired by Tim Angelikes block entropy check (if we decide to keep it we should ask him if he wants to show up as having contributed) and I noticed that there are a lot of single missings in the demo data that may have been counted as dropout in the previous calculation. I need to look into that further in the next couple of days!

**Comment by the-tave** [comment]
Thanks to this lovely thread (https://stackoverflow.com/questions/8506848/check-whether-vector-in-r-is-sequential ;) ), I incuded a check for single missings in the data in function add_dropout_idx - that works great now.
However, I still get a weird issue that compute_stats randomly produces the same line twice sometimes, leading to some drops being counted double. I'm looking into that  but if you, @mbannert have any idea what could be causing this, I'd be grateful for your input!

**Comment by the-tave** [comment]
resolved this issue - I rewrote add_dopout_idx with loops. The calculation takes a little longer, but it's robust!

**Comment by mbannert** [comment]
loops are almost never a good idea when there is a vectorized solution. Particularly when datasets get larger.  While I do understand that this should not be a bottleneck and hold publication back, I suggest to keep this issue open and tag with improvement. We can still move on and fix later. This does not only prevent forgetting about it, it also shows that we're aware that there should be better solution. Also it allows, those to whom the performance issues are more pressing to find a vectorized solution.

**Comment by the-tave** [comment]
found vectorized solution
