### ISSUE TITLE
Handle empty data.frame on Xi sq. tab

### ISSUE THREAD

**Issue by mbannert** [iscience-kn/dropR#3]
Kaplan-M. and visual inspector tab can handle it, too. I'd rather copy that behavior for the Xi sq. tab as opposed to checking the demo data checkbox by default. Imo, doing so might be a little distracting and fixing this issue is a better way of getting rid of the annoying error message.

What do you think @the-tave ?

**Comment by the-tave** [comment]
Hm, when I start the app (locally & online) the Vis tab also throws the Error: argument is of length zero. To me, it feels like the app should be rather instructional and the package should rather be used to analyze one's own data, so to me it wouldn't be distracting but rather helpful tbh

**Comment by mbannert** [comment]
I see "Please upload a dataset.
           Make sure to hit 'update data!' in the upload tab."
           
But you're right, the plot options don't look that nice and return an length 0 error.  My point was that one can check how the plotting functions handles this and than apply to the other case in analog fashion. Do you want to give it a shot in another branch?

**Comment by the-tave** [comment]
![image](https://github.com/iscience-kn/dropR/assets/120721022/7d8af395-930b-4bfb-a01b-b2f268f6913d)
I get both errors - although the red system error is more freaky for the user I think. I'll start a branch named demo-default to try out the behavior if the dataset is preselected
