### ISSUE TITLE
Kolmogorov test

### ISSUE THREAD

**Issue by mbannert** [iscience-kn/dropR#7]
as suggested by Ulf: 

Übrigens noch einbauen als ein Equivalence Test
für die Dropout-Kurven sollten wir
https://en.wikipedia.org/wiki/Kolmogorov

**Comment by the-tave** [comment]
@mbannert do you know what test Ulf means, could it be the Kolmogorov-Smirnov test? Because the wiki page he linked to redirects to a biography of Andrey Kolmogorov...

**Comment by mbannert** [comment]
Possibly, yes. Either ask him and/or think about what we're trying to achieve. I think Ulf wants to test whether experimental conditions make a difference w.r.t. dropout.

**Comment by the-tave** [comment]
Good advice ;) Ulf was talking about `stats::ks.test` to compare the most extreme experimental conditions w.r.t do. I'll create a branch to try implementation, but won't spend too much time fidgeting if I run into problems! (Ulf is quite keen on getting the publication process going soon and any further improvements and new features can still be implemented after publication)

**Comment by the-tave** [comment]
I will create a new branch for this and work on the implementation in the follwoing week - may not be featured in the "paper version" yet
