### ISSUE TITLE
decentralization in functions 

### ISSUE THREAD

**Issue by the-tave** [iscience-kn/dropR#9]
@mbannert Can you check that all functions that are now seperate have the same functionality as before? I cannot produce visualizations currently, "Error: unused argument(do_idx="drop_out_idx")"
Might have something to do with function f.k.a. extract_drop_from_df?

**Comment by mbannert** [comment]
Which version are you trying? Are running this locally on the latest branch? Worked for me from main yesterday.

**Comment by the-tave** [comment]
Interesting. Main branch works for me as well but documentation branch throws errors. I didn't change anything about functionality though... Do you have any idea on how I can troubleshoot this?

**Comment by the-tave** [comment]
fixed this!

**Comment by mbannert** [comment]
Was documentation a new branch ? 
If so, merge into new branches from time to time to be in line with recent development on main.
